throw语句里，类型是静态判断的，当使用

```c++
try
{
throw static_cast<Base*>(new Drived())
}
catch(Drived*)
{
//处理1
}
catch(Base*)
{
//处理2
}
//或者
try
{
    throw static_cast<Base&>(Drived())
}
catch(Drived&)
{
//处理1
}
catch(Base&)
{
//处理2
}
```

都会命中处理2，而不会命中处理1，这在catch中重新抛出时要注意

异常的Family特性，可以用来保证低层次的错误全部被其上层捕获，如果不捕获，由于其更上层使用的异常是从另外的分支继承来的，所以也不会捕获低层次的异常，这会直接导致程序终止，这样就可以强制每个层次保证异常安全，但是这需要完整的测试流程，否则不仅不会有效果，反而会增大程序崩溃的概率。

